export GNUPGHOME=${HOME}/.config/gnupg
export NVM_DIR=${HOME}/.config/nvm
export PARALLEL_HOME=${HOME}/.config/parallel
export PYENV_ROOT=${HOME}/.config/pyenv
export ZDOTDIR=${HOME}/.config/zsh
export TEXMFHOME=${HOME}/.local/share/texmf
export CARGO_HOME=${HOME}/.cache/cargo
export RUSTUP_HOME=${HOME}/.config/rustup

export PATH="${PYENV_ROOT/bin}:${PATH}"

export npm_config_devdir=${HOME}/.cache/node-gyp
