export GNUPGHOME=${HOME}/.config/gnupg
export NVM_DIR=${HOME}/.config/nvm
export PARALLEL_HOME=${HOME}/.config/parallel
export PYENV_ROOT=${HOME}/.config/pyenv
export TEXMFHOME=${HOME}/.local/share/texmf
export CARGO_HOME=${HOME}/.cache/cargo
export RUSTUP_HOME=${HOME}/.config/rustup
export LESSHISTFILE=${HOME}/.cache/lesshst
export LESSHISTSIZE=10000

export PATH="${PYENV_ROOT/bin}:${PATH}"

export npm_config_devdir=${HOME}/.cache/node-gyp

# Zsh settings
export ZDOTDIR=${HOME}/.config/zsh
export ZSH=${HOME}/.config/oh-my-zsh
